---
title: "Final Project - BIOS 6643"
author: "Dominic Adducci"
output: html_document
---

```{r, echo = F}

library(tidyverse)
library(kableExtra)
library(broom)
library(mgcv)

```

```{r, echo = F}

project2_data_raw <- readRDS("C:/Users/domin/Documents/Biostatistics Masters Program/Fall 2023/BIOS 6643 - ADL/BIOS6643_ALD/Final Project/ProcessedData/project2_data.rds")

# Turning the ID column in to a factor, and logging psill and range. 
project2_data <- project2_data_raw %>% 
  mutate(ID = factor(ID),
         log_psill = log(psill),
         log_range = log(range)) %>%
  mutate(Fibrosis = recode(Fibrosis,
                           No = 0,Yes = 1),
         Traction_Bronchiectasis = recode(Traction_Bronchiectasis,
                                          No = 0,Yes = 1),
         Med_Lymphadenopathy = recode(Med_Lymphadenopathy,
                                      No = 0, Yes = 1))

left_lung_data <- project2_data %>% filter(lung == "Left")
right_lung_data <- project2_data %>% filter(lung == "Right")

```

# Left Lung log(Psill) 

```{r, echo = F}

# Left Lung log(Psill) models including race. 

# Model where Fibrosis is the primary predictor.
lp_fib_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Fibrosis,bs = "ps"),
                       data = left_lung_data, family = gaussian, method = "ML")

lp_fib_race_mod_sum <- tidy(lp_fib_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Mediastinal Lymphadenopathy is the primary predictor.
lp_med_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Med_Lymphadenopathy,bs = "ps"), 
                       data = left_lung_data, family = gaussian, method = "ML")

lp_med_race_mod_sum <- tidy(lp_med_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Traction Bronchiectasis is the primary predictor. 
lp_tra_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Traction_Bronchiectasis,bs = "ps"),
                       data = left_lung_data, family = gaussian, method = "ML")

lp_tra_race_mod_sum <- tidy(lp_tra_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1 is the primary predictor. 
lp_fev1_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) + 
                          BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                          s(slice_normalized,by = POSTFEV1,bs = "ps"), 
                        data = left_lung_data, family = gaussian, method = "ML")

lp_fev1_race_mod_sum <- tidy(lp_fev1_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FVC is the primary predictor. 
lp_fvc_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = POSTFVC,bs = "ps"),
                       data = left_lung_data, family = gaussian, method = "ML") 

lp_fvc_race_mod_sum <- tidy(lp_fvc_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1/FVC is the primary predictor. 
lp_fev1_fvc_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                              BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                              s(slice_normalized,by = POSTFEVFVC,bs = "ps"), 
                            data = left_lung_data, family = gaussian, method = "ML") 

lp_fev1_fvc_race_mod_sum <- tidy(lp_fev1_fvc_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Making a table of the results.
lp_race_mods_df <- rbind(lp_fib_race_mod_sum,lp_med_race_mod_sum,
                         lp_tra_race_mod_sum,lp_fev1_race_mod_sum,
                         lp_fvc_race_mod_sum,lp_fev1_fvc_race_mod_sum) 

lp_race_mods_table <- kbl(lp_race_mods_df,
                          caption = "Left Lung Psill - Adjusted for Race",
                          col.names = c("Term","Estimate",
                                        "Std. Error","P-Value"),
                          booktabs = T, align = "cc", longtable = T) %>%
  kable_styling(latex_options = c("HOLD_position","repeat_header")) %>%
  group_rows("Fibrosis",1,7) %>%
  group_rows("Mediastinal Lymphadenopathy",8,14) %>%
  group_rows("Traction Bronchiectasis",15,21) %>%
  group_rows("FEV1",22,28) %>%
  group_rows("FVC",29,35) %>%
  group_rows("FEV1/FVC",36,42)

```

```{r, echo = F}

# Left lung log(psill) models not including race. 

# Model where Fibrosis is the primary predictor.
lp_fib_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") +
                    s(slice_normalized,by = Fibrosis,bs = "ps"),
                  data = left_lung_data, family = gaussian, method = "ML")

lp_fib_mod_sum <- tidy(lp_fib_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Mediastinal Lymphadenopathy is the primary predictor.
lp_med_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") + 
                    s(slice_normalized,by = Med_Lymphadenopathy,bs = "ps"), 
                  data = left_lung_data, family = gaussian, method = "ML")

lp_med_mod_sum <- tidy(lp_med_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Traction Bronchiectasis is the primary predictor. 
lp_tra_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") + 
                    s(slice_normalized,by = Traction_Bronchiectasis,bs = "ps"),
                  data = left_lung_data, family = gaussian, method = "ML")

lp_tra_mod_sum <- tidy(lp_tra_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1 is the primary predictor. 
lp_fev1_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) + 
                     BMI + Age + Gender + Height + s(ID,bs = "re") +
                     s(slice_normalized,by = POSTFEV1,bs = "ps"),
                   data = left_lung_data, family = gaussian, method = "ML")

lp_fev1_mod_sum <- tidy(lp_fev1_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FVC is the primary predictor. 
lp_fvc_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") +
                    s(slice_normalized,by = POSTFVC,bs = "bs"),
                  data = left_lung_data, family = gaussian, method = "ML") 

lp_fvc_mod_sum <- tidy(lp_fvc_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1/FVC is the primary predictor. 
lp_fev1_fvc_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + s(ID,bs = "re") + 
                         s(slice_normalized,by = POSTFEVFVC,bs = "ps"), 
                       data = left_lung_data, family = gaussian, method = "ML") 

lp_fev1_fvc_mod_sum <- tidy(lp_fev1_fvc_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Making a table of results. 
lp_mods_df <- rbind(lp_fib_mod_sum,lp_med_mod_sum,lp_tra_mod_sum,
                    lp_fev1_mod_sum,lp_fvc_mod_sum,lp_fev1_fvc_mod_sum)

lp_mods_table <- kbl(lp_mods_df,
                     caption = "Left Lung Psill - Not Adjusted for Race",
                     col.names = c("Term","Estimate",
                                   "Std. Error","P-Value"),
                     booktabs = T, align = "cc", longtable = T) %>%
  kable_styling(latex_options = c("HOLD_position","repeat_header")) %>%
  group_rows("Fibrosis",1,5) %>%
  group_rows("Mediastinal Lymphadenopathy",6,10) %>%
  group_rows("Traction Bronchiectasis",11,15) %>%
  group_rows("FEV1",16,20) %>%
  group_rows("FVC",21,25) %>%
  group_rows("FEV1/FVC",26,30)

```

```{r, echo = F}

lp_race_mods_table

lp_mods_table

```

# Left Lung log(Range)

```{r, echo = F}

# Left Lung log(Range) models including race. 

# Model where Fibrosis is the primary predictor.
lr_fib_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Fibrosis,bs = "ps"),
                       data = left_lung_data, family = gaussian, method = "ML")

lr_fib_race_mod_sum <- tidy(lr_fib_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Mediastinal Lymphadenopathy is the primary predictor.
lr_med_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Med_Lymphadenopathy,bs = "ps"), 
                       data = left_lung_data, family = gaussian, method = "ML")

lr_med_race_mod_sum <- tidy(lr_med_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Traction Bronchiectasis is the primary predictor. 
lr_tra_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Traction_Bronchiectasis,bs = "ps"), 
                       data = left_lung_data, family = gaussian, method = "ML")

lr_tra_race_mod_sum <- tidy(lr_tra_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1 is the primary predictor. 
lr_fev1_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) + 
                          BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                          s(slice_normalized,by = POSTFEV1,bs = "ps"), 
                        data = left_lung_data, family = gaussian, method = "ML")

lr_fev1_race_mod_sum <- tidy(lr_fev1_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FVC is the primary predictor. 
lr_fvc_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = POSTFVC,bs = "ps"), 
                       data = left_lung_data, family = gaussian, method = "ML") 

lr_fvc_race_mod_sum <- tidy(lr_fvc_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1/FVC is the primary predictor. 
lr_fev1_fvc_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                              BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                              s(slice_normalized,by = POSTFEVFVC,bs = "ps"), 
                            data = left_lung_data, family = gaussian, method = "ML") 

lr_fev1_fvc_race_mod_sum <- tidy(lr_fev1_fvc_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Making a table of the results.
lr_race_mods_df <- rbind(lr_fib_race_mod_sum,lr_med_race_mod_sum,
                         lr_tra_race_mod_sum,lr_fev1_race_mod_sum,
                         lr_fvc_race_mod_sum,lr_fev1_fvc_race_mod_sum) 

lr_race_mods_table <- kbl(lr_race_mods_df,
                          caption = "Left Lung Range - Adjusted for Race",
                          col.names = c("Term","Estimate",
                                        "Std. Error","P-Value"),
                          booktabs = T, align = "cc", longtable = T) %>%
  kable_styling(latex_options = c("HOLD_position","repeat_header")) %>%
  group_rows("Fibrosis",1,7) %>%
  group_rows("Mediastinal Lymphadenopathy",8,14) %>%
  group_rows("Traction Bronchiectasis",15,21) %>%
  group_rows("FEV1",22,28) %>%
  group_rows("FVC",29,35) %>%
  group_rows("FEV1/FVC",36,42)

```

```{r, echo = F}

# Left lung log(Range) models not including race. 

# Model where Fibrosis is the primary predictor.
lr_fib_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") + 
                    s(slice_normalized,by = Fibrosis,bs = "ps"), 
                  data = left_lung_data, family = gaussian, method = "ML")

lr_fib_mod_sum <- tidy(lr_fib_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Mediastinal Lymphadenopathy is the primary predictor.
lr_med_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") + 
                    s(slice_normalized,by = Med_Lymphadenopathy,bs = "ps"), 
                  data = left_lung_data, family = gaussian, method = "ML")

lr_med_mod_sum <- tidy(lr_med_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Traction Bronchiectasis is the primary predictor. 
lr_tra_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") + 
                    s(slice_normalized,by = Traction_Bronchiectasis,bs = "ps"), 
                  data = left_lung_data, family = gaussian, method = "ML")

lr_tra_mod_sum <- tidy(lr_tra_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1 is the primary predictor. 
lr_fev1_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) + 
                     BMI + Age + Gender + Height + s(ID,bs = "re") +
                     s(slice_normalized,by = POSTFEV1,bs = "ps"),
                   data = left_lung_data, family = gaussian, method = "ML")

lr_fev1_mod_sum <- tidy(lr_fev1_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FVC is the primary predictor. 
lr_fvc_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") +
                    s(slice_normalized,by = POSTFVC,bs = "ps"),
                  data = left_lung_data, family = gaussian, method = "ML") 

lr_fvc_mod_sum <- tidy(lr_fvc_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1/FVC is the primary predictor. 
lr_fev1_fvc_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + s(ID,bs = "re") + 
                         s(slice_normalized,by = POSTFEVFVC,bs = "ps"), 
                       data = left_lung_data, family = gaussian, method = "ML") 

lr_fev1_fvc_mod_sum <- tidy(lr_fev1_fvc_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Making a table of results. 
lr_mods_df <- rbind(lr_fib_mod_sum,lr_med_mod_sum,lr_tra_mod_sum,
                    lr_fev1_mod_sum,lr_fvc_mod_sum,lr_fev1_fvc_mod_sum)

lr_mods_table <- kbl(lr_mods_df,
                     caption = "Left Lung Range - Not Adjusted for Race",
                     col.names = c("Term","Estimate",
                                   "Std. Error","P-Value"),
                     booktabs = T, align = "cc", longtable = T) %>%
  kable_styling(latex_options = c("HOLD_position","repeat_header")) %>%
  group_rows("Fibrosis",1,5) %>%
  group_rows("Mediastinal Lymphadenopathy",6,10) %>%
  group_rows("Traction Bronchiectasis",11,15) %>%
  group_rows("FEV1",16,20) %>%
  group_rows("FVC",21,25) %>%
  group_rows("FEV1/FVC",26,30)

```

```{r, echo = F}

lr_race_mods_table

lr_mods_table

```

# Right Lung log(Psill) 

```{r, echo = F}

# Right Lung log(Psill) models including race. 

# Model where Fibrosis is the primary predictor.
rp_fib_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Fibrosis,bs = "ps"), 
                       data = right_lung_data, family = gaussian, method = "ML")

rp_fib_race_mod_sum <- tidy(rp_fib_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Mediastinal Lymphadenopathy is the primary predictor.
rp_med_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Med_Lymphadenopathy,bs = "ps"), 
                       data = right_lung_data, family = gaussian, method = "ML")

rp_med_race_mod_sum <- tidy(rp_med_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Traction Bronchiectasis is the primary predictor. 
rp_tra_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Traction_Bronchiectasis,bs = "ps"), 
                       data = right_lung_data, family = gaussian, method = "ML")

rp_tra_race_mod_sum <- tidy(rp_tra_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1 is the primary predictor. 
rp_fev1_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) + 
                          BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                          s(slice_normalized,by = POSTFEV1,bs = "ps"), 
                        data = right_lung_data, family = gaussian, method = "ML")

rp_fev1_race_mod_sum <- tidy(rp_fev1_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FVC is the primary predictor. 
rp_fvc_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = POSTFVC,bs = "ps"), 
                       data = right_lung_data, family = gaussian, method = "ML") 

rp_fvc_race_mod_sum <- tidy(rp_fvc_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1/FVC is the primary predictor. 
rp_fev1_fvc_race_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                              BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                              s(slice_normalized,by = POSTFEVFVC,bs = "ps"), 
                            data = right_lung_data, family = gaussian, method = "ML") 

rp_fev1_fvc_race_mod_sum <- tidy(rp_fev1_fvc_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Making a table of the results.
rp_race_mods_df <- rbind(rp_fib_race_mod_sum,rp_med_race_mod_sum,
                         rp_tra_race_mod_sum,rp_fev1_race_mod_sum,
                         rp_fvc_race_mod_sum,rp_fev1_fvc_race_mod_sum) 

rp_race_mods_table <- kbl(rp_race_mods_df,
                          caption = "Right Lung Psill - Adjusted for Race",
                          col.names = c("Term","Estimate",
                                        "Std. Error","P-Value"),
                          booktabs = T, align = "cc", longtable = T) %>%
  kable_styling(latex_options = c("HOLD_position","repeat_header")) %>%
  group_rows("Fibrosis",1,7) %>%
  group_rows("Mediastinal Lymphadenopathy",8,14) %>%
  group_rows("Traction Bronchiectasis",15,21) %>%
  group_rows("FEV1",22,28) %>%
  group_rows("FVC",29,35) %>%
  group_rows("FEV1/FVC",36,42)

```

```{r, echo = F}

# Right lung log(psill) models not including race. 

# Model where Fibrosis is the primary predictor.
rp_fib_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") +
                    s(slice_normalized,by = Fibrosis,bs = "ps"),
                  data = right_lung_data, family = gaussian, method = "ML")

rp_fib_mod_sum <- tidy(rp_fib_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Mediastinal Lymphadenopathy is the primary predictor.
rp_med_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") + 
                    s(slice_normalized,by = Med_Lymphadenopathy,bs = "ps"), 
                  data = right_lung_data, family = gaussian, method = "ML")

rp_med_mod_sum <- tidy(rp_med_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Traction Bronchiectasis is the primary predictor. 
rp_tra_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") + 
                    s(slice_normalized,by = Traction_Bronchiectasis,bs = "ps"), 
                  data = right_lung_data, family = gaussian, method = "ML")

rp_tra_mod_sum <- tidy(rp_tra_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1 is the primary predictor. 
rp_fev1_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) + 
                     BMI + Age + Gender + Height + s(ID,bs = "re") +
                     s(slice_normalized,by = POSTFEV1,bs = "ps"),
                   data = right_lung_data, family = gaussian, method = "ML")

rp_fev1_mod_sum <- tidy(rp_fev1_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FVC is the primary predictor. 
rp_fvc_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") +
                    s(slice_normalized,by = POSTFVC,bs = "ps"),
                  data = right_lung_data, family = gaussian, method = "ML") 

rp_fvc_mod_sum <- tidy(rp_fvc_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1/FVC is the primary predictor. 
rp_fev1_fvc_mod <- gam(log_psill ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + s(ID,bs = "re") + 
                         s(slice_normalized,by = POSTFEVFVC,bs = "ps"), 
                       data = right_lung_data, family = gaussian, method = "ML") 

rp_fev1_fvc_mod_sum <- tidy(rp_fev1_fvc_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Making a table of results. 
rp_mods_df <- rbind(rp_fib_mod_sum,rp_med_mod_sum,rp_tra_mod_sum,
                    rp_fev1_mod_sum,rp_fvc_mod_sum,rp_fev1_fvc_mod_sum)

rp_mods_table <- kbl(rp_mods_df,
                     caption = "Right Lung Psill - Not Adjusted for Race",
                     col.names = c("Term","Estimate",
                                   "Std. Error","P-Value"),
                     booktabs = T, align = "cc", longtable = T) %>%
  kable_styling(latex_options = c("HOLD_position","repeat_header")) %>%
  group_rows("Fibrosis",1,5) %>%
  group_rows("Mediastinal Lymphadenopathy",6,10) %>%
  group_rows("Traction Bronchiectasis",11,15) %>%
  group_rows("FEV1",16,20) %>%
  group_rows("FVC",21,25) %>%
  group_rows("FEV1/FVC",26,30)

```

```{r, echo = F}

rp_race_mods_table

rp_mods_table

```

# Right Lung log(Range)

```{r, echo = F}

# Right Lung log(Range) models including race. 

# Model where Fibrosis is the primary predictor.
rr_fib_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Fibrosis,bs = "ps"), 
                       data = right_lung_data, family = gaussian, method = "ML")

rr_fib_race_mod_sum <- tidy(rr_fib_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Mediastinal Lymphadenopathy is the primary predictor.
rr_med_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Med_Lymphadenopathy,bs = "ps"), 
                       data = right_lung_data, family = gaussian, method = "ML")

rr_med_race_mod_sum <- tidy(rr_med_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Traction Bronchiectasis is the primary predictor. 
rr_tra_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = Traction_Bronchiectasis,bs = "ps"), 
                       data = right_lung_data, family = gaussian, method = "ML")

rr_tra_race_mod_sum <- tidy(rr_tra_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1 is the primary predictor. 
rr_fev1_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) + 
                          BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                          s(slice_normalized,by = POSTFEV1,bs = "ps"), 
                        data = right_lung_data, family = gaussian, method = "ML")

rr_fev1_race_mod_sum <- tidy(rr_fev1_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FVC is the primary predictor. 
rr_fvc_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                         s(slice_normalized,by = POSTFVC,bs = "ps"), 
                       data = right_lung_data, family = gaussian, method = "ML") 

rr_fvc_race_mod_sum <- tidy(rr_fvc_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1/FVC is the primary predictor. 
rr_fev1_fvc_race_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                              BMI + Age + Gender + Height + Race + s(ID,bs = "re") + 
                              s(slice_normalized,by = POSTFEVFVC,bs = "ps"), 
                            data = right_lung_data, family = gaussian, method = "ML") 

rr_fev1_fvc_race_mod_sum <- tidy(rr_fev1_fvc_race_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Making a table of the results.
rr_race_mods_df <- rbind(rr_fib_race_mod_sum,rr_med_race_mod_sum,
                         rr_tra_race_mod_sum,rr_fev1_race_mod_sum,
                         rr_fvc_race_mod_sum,rr_fev1_fvc_race_mod_sum) 

rr_race_mods_table <- kbl(rr_race_mods_df,
                          caption = "Right Lung Range - Adjusted for Race",
                          col.names = c("Term","Estimate",
                                        "Std. Error","P-Value"),
                          booktabs = T, align = "cc", longtable = T) %>%
  kable_styling(latex_options = c("HOLD_position","repeat_header")) %>%
  group_rows("Fibrosis",1,7) %>%
  group_rows("Mediastinal Lymphadenopathy",8,14) %>%
  group_rows("Traction Bronchiectasis",15,21) %>%
  group_rows("FEV1",22,28) %>%
  group_rows("FVC",29,35) %>%
  group_rows("FEV1/FVC",36,42)

```

```{r, echo = F}

# Right lung log(Range) models not including race. 

# Model where Fibrosis is the primary predictor.
rr_fib_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") +
                    s(slice_normalized,by = Fibrosis,bs = "ps"),
                  data = right_lung_data, family = gaussian, method = "ML")

rr_fib_mod_sum <- tidy(rr_fib_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Mediastinal Lymphadenopathy is the primary predictor.
rr_med_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") + 
                    s(slice_normalized,by = Med_Lymphadenopathy,bs = "ps"), 
                  data = right_lung_data, family = gaussian, method = "ML")

rr_med_mod_sum <- tidy(rr_med_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where Traction Bronchiectasis is the primary predictor. 
rr_tra_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") + 
                    s(slice_normalized,by = Traction_Bronchiectasis,bs = "ps"), 
                  data = right_lung_data, family = gaussian, method = "ML")

rr_tra_mod_sum <- tidy(rr_tra_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1 is the primary predictor. 
rr_fev1_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) + 
                     BMI + Age + Gender + Height + s(ID,bs = "re") +
                     s(slice_normalized,by = POSTFEV1,bs = "ps"),
                   data = right_lung_data, family = gaussian, method = "ML")

rr_fev1_mod_sum <- tidy(rr_fev1_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FVC is the primary predictor. 
rr_fvc_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                    BMI + Age + Gender + Height + s(ID,bs = "re") +
                    s(slice_normalized,by = POSTFVC,bs = "ps"),
                  data = right_lung_data, family = gaussian, method = "ML") 

rr_fvc_mod_sum <- tidy(rr_fvc_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Model where FEV1/FVC is the primary predictor. 
rr_fev1_fvc_mod <- gam(log_range ~ s(slice_normalized,bs = "ps",m = c(2,2)) +
                         BMI + Age + Gender + Height + s(ID,bs = "re") + 
                         s(slice_normalized,by = POSTFEVFVC,bs = "ps"), 
                       data = right_lung_data, family = gaussian, method = "ML") 

rr_fev1_fvc_mod_sum <- tidy(rr_fev1_fvc_mod, parametric = T) %>%
  select(term, estimate, std.error, p.value) %>%
  mutate(p.value = format.pval(p.value, digits = 3))

# Making a table of results. 
rr_mods_df <- rbind(rr_fib_mod_sum,rr_med_mod_sum,rr_tra_mod_sum,
                    rr_fev1_mod_sum,rr_fvc_mod_sum,rr_fev1_fvc_mod_sum)

rr_mods_table <- kbl(rr_mods_df,
                     caption = "Right Lung Range - Not Adjusted for Race",
                     col.names = c("Term","Estimate",
                                   "Std. Error","P-Value"),
                     booktabs = T, align = "cc", longtable = T) %>%
  kable_styling(latex_options = c("HOLD_position","repeat_header")) %>%
  group_rows("Fibrosis",1,5) %>%
  group_rows("Mediastinal Lymphadenopathy",6,10) %>%
  group_rows("Traction Bronchiectasis",11,15) %>%
  group_rows("FEV1",16,20) %>%
  group_rows("FVC",21,25) %>%
  group_rows("FEV1/FVC",26,30)

```

```{r, echo = F}

rr_race_mods_table 

rr_mods_table 

```




